{% set name = "sqlalchemy-access" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 89174a94e0ebd6c32470282d143aef0c0fbe3aafdee2c40956cd417648cb317e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sqlalchemy >=2.0.0
    - pyodbc >=4.0.27
    - pywin32-on-windows
    - __win

test:
  imports:
    - sqlalchemy_access
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gordthompson/sqlalchemy-access
  summary: MS Access for SQLAlchemy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jepegit
