{% set name = "sqlalchemy-access" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-access-{{ version }}.tar.gz
  sha256: 61b577dddc7975f64a567a711105450f56a1d5057e7f0ef1c5772b62a7bc2b1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - sqlalchemy >=2.0.0
    - pyodbc >=4.0.27
    - pywin32-on-windows
    - __win

test:
  imports:
    - sqlalchemy_access
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gordthompson/sqlalchemy-access
  summary: MS Access for SQLAlchemy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jepegit
